# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    machine: true
    working_directory: ~/ufd19_telegram
    steps:
      - checkout
      - run:
          name: Setup .env
          command: |
            echo TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN >> .env
            echo DIALOGFLOW_PROJECT_ID=$DIALOGFLOW_PROJECT_ID >> .env
            echo DIALOGFLOW_PROJECT_PRIVATE_KEY=$DIALOGFLOW_PROJECT_PRIVATE_KEY >> .env
            echo DIALOGFLOW_PROJECT_EMAIL=$DIALOGFLOW_PROJECT_EMAIL >> .env
      - run:
          name: Build Docker image
          command: docker build -t mallau.net:8080/ufd19_telegram .
      - run:
          name: Push to mallau Docker Registry
          command: |
            echo $MALLAU_DOCKER_PASSWORD | docker login mallau.net:8080 -u $MALLAU_DOCKER_LOGIN --password-stdin
            docker push mallau.net:8080/ufd19_telegram
            docker logout mallau.net:8080
  deploy:
    machine: true
    steps:
      - run:
          name: Deploy over SSH
          command: |
            sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "./deploy_ufd19_server.sh mallau.net:8080/ufd19_telegram"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
